# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: MIT
#
variables:
  linux-docker-image: 'vcpkgandroidwus3.azurecr.io/vcpkg-android:2024-07-11'

parameters:
  - name: vcpkgToolSha
    displayName: 'Custom SHA of vcpkg-tool to use rather than bootstrap'
    type: string
    default: a5bc282011d22792c4f6d0e4a4424d9b3ab8a9eb
  - name: tripletPattern
    displayName: 'Enable triplets which contain this substring'
    type: string
    default: '-'

jobs:
- template: windows/azure-pipelines.yml
  parameters:
    jobName: x86_windows
    vcpkgToolSha: ${{ parameters.vcpkgToolSha }}
    tripletPattern: ${{ parameters.tripletPattern }}

- template: windows/azure-pipelines.yml
  parameters:
    jobName: x64_windows
    vcpkgToolSha: ${{ parameters.vcpkgToolSha }}
    tripletPattern: ${{ parameters.tripletPattern }}

- template: windows/azure-pipelines.yml
  parameters:
    jobName: x64_windows_static
    vcpkgToolSha: ${{ parameters.vcpkgToolSha }}
    tripletPattern: ${{ parameters.tripletPattern }}

- template: windows/azure-pipelines.yml
  parameters:
    jobName: x64_windows_static_md
    vcpkgToolSha: ${{ parameters.vcpkgToolSha }}
    tripletPattern: ${{ parameters.tripletPattern }}

- template: windows/azure-pipelines.yml
  parameters:
    jobName: x64_uwp
    vcpkgToolSha: ${{ parameters.vcpkgToolSha }}
    tripletPattern: ${{ parameters.tripletPattern }}

- template: windows/azure-pipelines.yml
  parameters:
    jobName: arm64_windows
    vcpkgToolSha: ${{ parameters.vcpkgToolSha }}
    tripletPattern: ${{ parameters.tripletPattern }}

- template: windows/azure-pipelines.yml
  parameters:
    jobName: arm64_uwp
    vcpkgToolSha: ${{ parameters.vcpkgToolSha }}
    tripletPattern: ${{ parameters.tripletPattern }}

- template: osx/azure-pipelines.yml
  parameters:
    jobName: x64_osx
    poolName: 'PrOsx-2024-07-12'
    vcpkgToolSha: ${{ parameters.vcpkgToolSha }}
    tripletPattern: ${{ parameters.tripletPattern }}

- template: osx/azure-pipelines.yml
  parameters:
    jobName: arm64_osx
    poolName: 'PrOsx-2024-07-12-arm64'
    vcpkgToolSha: ${{ parameters.vcpkgToolSha }}
    tripletPattern: ${{ parameters.tripletPattern }}

- template: linux/azure-pipelines.yml
  parameters:
    jobName: x64_linux
    vcpkgToolSha: ${{ parameters.vcpkgToolSha }}
    tripletPattern: ${{ parameters.tripletPattern }}

- template: android/azure-pipelines.yml
  parameters:
    jobName: arm_neon_android
    dockerImage: $(linux-docker-image)
    tripletPattern: ${{ parameters.tripletPattern }}

- template: android/azure-pipelines.yml
  parameters:
    jobName: x64_android
    dockerImage: $(linux-docker-image)
    tripletPattern: ${{ parameters.tripletPattern }}

- template: android/azure-pipelines.yml
  parameters:
    jobName: arm64_android
    dockerImage: $(linux-docker-image)
    tripletPattern: ${{ parameters.tripletPattern }}
